### ISSUE TITLE
If I try to use a flag in CLI that is not defined, gets a panic

### ISSUE THREAD

**Issue by lstep** [tucnak/climax#1]
If try tu run a small minimal app with climax, that doesn't have 't' flag defined, I get a panic:

```
 # ./stellar-stacy serve -t=3
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x40 pc=0x4814b6]

goroutine 1 [running]:
github.com/tucnak/climax.parseContext(0xc8200a0410, 0x1, 0x1, 0xc82007e260, 0x1, 0x1, 0x1, 0x0, 0x0)
    /home/foo/go/src/github.com/tucnak/climax/context.go:97 +0x496
github.com/tucnak/climax.Application.Run(0x78c890, 0x6, 0x7c1b80, 0x10, 0x821350, 0x13, 0xc8200ba180, 0x1, 0x1, 0x0, ...)
    /home/foo/go/src/github.com/tucnak/climax/application.go:117 +0xa19
main.main()
    /home/foo/go/src/myserver/myroot/stellar-stacy/main.go:21 +0x173
```

When launching it with a flag that **exists**, it works fine. The `climax.Command` structure I used is the one defined on the main github page.

**Comment by tucnak** [comment]
@lstep My bad, will fix ASAP (once I get to my PC)
